name: Update Content

on:
  workflow_dispatch:

concurrency:
  group: update-content
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  update_content:
    name: Update Content
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: true
          fetch-depth: 0
      - name: Add subtree deploy key
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/content_repo.key
          chmod 600 ~/.ssh/content_repo.key
          cat >>~/.ssh/config <<END
          Host content_repo
            HostName github.com
            User git
            IdentityFile ~/.ssh/content_repo.key
          END
        env:
          SSH_KEY: ${{ secrets.CONTENT_REPO_DEPLOY_KEY }}

      - run: |
          git config --global user.email "github-actions[bot]"
          git config --global user.name "github-actions[bot]@users.noreply.github.com"

      - run: git branch -D update-content || true

      - run: git checkout -b update-content

      - run: git subtree pull --prefix content content_repo:emmatown/keystatic-content-test main --squash

      - run: git push --force --set-upstream origin update-content
