name: Update Content

on:
  workflow_dispatch:

concurrency:
  group: update-content
  cancel-in-progress: true

permissions: {}

jobs:
  update_content:
    name: Update Content
    runs-on: ubuntu-latest
    strategy:
      matrix:
        branch:
          - main
          - other-env
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: true
          token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
          fetch-depth: 0
          ref: ${{matrix.branch}}
      - name: Add subtree deploy key
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/content_repo.key
          chmod 600 ~/.ssh/content_repo.key
          cat >>~/.ssh/config <<END
          Host content_repo
            HostName github.com
            User git
            IdentityFile ~/.ssh/content_repo.key
          END
        env:
          SSH_KEY: ${{ secrets.CONTENT_REPO_DEPLOY_KEY }}

      - run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      - run: git branch -D update-content-${{matrix.branch}} || true

      - run: git checkout -b update-content-${{matrix.branch}}

      - run: git subtree pull --prefix content content_repo:emmatown/keystatic-content-test main --squash

      - run: git push --force --set-upstream origin update-content-${{matrix.branch}}

      - uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
          script: |
            const { createOrUpdateContentPR } = await import('${{ github.workspace }}/.github/content-pr.mjs')

            await createOrUpdateContentPR(github, "${{matrix.branch}}")
